version: "3.9"

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: ${PLEX_NAME}
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - "./config/plex:/config"
      - "${MOVIES_DIR}:/movies"
      - "${SHOWS_DIR}:/tv"
    restart: unless-stopped
    networks:
      - media_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: ${QBITTORRENT_NAME}
    ports:
      - "${QBITTORRENT_PORT}:${QBITTORRENT_PORT}"  # Web UI
      - "6881:6881"  # Torrent port
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=${QBITTORRENT_PORT}
    volumes:
      - "./config/qbittorrent:/config"
      - "${DOWNLOADS_DIR}:/downloads"
    restart: unless-stopped
    networks:
      - media_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: ${RADARR_NAME}
    ports:
      - "${RADARR_PORT}:${RADARR_PORT}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "./config/radarr:/config"
      - "${MOVIES_DIR}:/movies"
      - "${DOWNLOADS_DIR}:/downloads"
    restart: unless-stopped
    networks:
      - media_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: ${SONARR_NAME}
    ports:
      - "${SONARR_PORT}:${SONARR_PORT}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "./config/sonarr:/config"
      - "${SHOWS_DIR}:/tv"
      - "${DOWNLOADS_DIR}:/downloads"
    restart: unless-stopped
    networks:
      - media_network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: ${PROWLARR_NAME}
    ports:
      - "${PROWLARR_PORT}:${PROWLARR_PORT}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "./config/prowlarr:/config"
    restart: unless-stopped
    networks:
      - media_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - plex
      - qbittorrent
      - radarr
      - sonarr
      - prowlarr
    networks:
      - media_network


networks:
  media_network:
    driver: bridge