include:
  - path:
    - ./config/docker-compose.yaml
    - ./apps/monitoring/docker-compose.yaml
    - ./apps/media/docker-compose.yaml
    - ./apps/automation/docker-compose.yaml
    - ./apps/management/docker-compose.yaml
    - ./apps/networking/docker-compose.yaml

networks:
  media_network:
    driver: bridge
    
volumes:
  movies:
    driver: local
    driver_opts:
      type: none
      device: ${MOVIES_DIR}
      o: bind

  shows:
    driver: local
    driver_opts:
      type: none
      device: ${SHOWS_DIR}
      o: bind

  downloads:
    driver: local
    driver_opts:
      type: none
      device: ${DOWNLOADS_DIR}
      o: bind