x-service: &service
  restart: unless-stopped
  networks:
    - media_network

x-user: &user
  <<: *service
  environment:
    - PUID=${USER_ID}
    - PGID=${GROUP_ID}
    - TZ=${TIMEZONE}

services:
  adguard:
    <<: *service
    image: adguard/adguardhome:latest
    container_name: ${ADGUARD_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`${ADGUARD_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.adguard.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.adguard.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.adguard.loadbalancer.server.port=${ADGUARD_PORT}"
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:${ADGUARD_PORT}/" ]
      interval: 30s
      retries: 10

  traefik:
    <<: *service
    image: traefik:latest
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.traefik.service=api@internal"
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 8010:8080
      - 8443:8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./acme/acme.json:/acme.json

  # nginx:
  #   <<: *service
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
      # - "443:443"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
  #     - ./nginx/couch-tomatoes.me.crt:/etc/ssl/certs/couch-tomatoes.me