x-service: &service
  restart: unless-stopped
  networks:
    - media_network

x-user: &user
  <<: *service
  environment:
    - PUID=${USER_ID}
    - PGID=${GROUP_ID}
    - TZ=${TIMEZONE}

services:
  traefix:
    <<: *service
    image: traefik:v3.0
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      # - 80:80
      - 443:443
      - 8010:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./acme/acme.json:/acme.json
    command:
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

  nginx:
    <<: *service
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/couch-tomatoes.me.crt:/etc/ssl/certs/couch-tomatoes.me