x-service: &service
  restart: unless-stopped
  networks:
    - media_network

x-user: &user
  <<: *service
  environment:
    - PUID=${USER_ID}
    - PGID=${GROUP_ID}
    - TZ=${TIMEZONE}

services:
  emby:
    <<: *user
    image: lscr.io/linuxserver/emby:latest
    container_name: ${EMBY_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.rule=Host(`${EMBY_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.emby.entrypoints=websecure"
      - "traefik.http.routers.emby.tls.certresolver=letsencrypt"
      - "traefik.http.routers.emby.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.emby.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.emby.loadbalancer.server.port=${EMBY_PORT}"
    volumes:
      - ./emby:/config
      - shows:/data/tvshows
      - movies:/data/movies
    # ports:
    #   - ${EMBY_PORT}:${EMBY_PORT}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8096/emby/system/ping" ]
      interval: 30s
      retries: 10

  jellyfin:
    <<: *user
    image: jellyfin/jellyfin:latest
    container_name: ${JELLYFIN_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure-public"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.jellyfin.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=${JELLYFIN_PORT}"
    group_add:
      - "992"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./jellyfin:/config
      - shows:/data/tvshows
      - movies:/data/movies
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8096/health" ]
      interval: 30s
      retries: 10

  seerr:
    <<: *service
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: ${SEERR_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seerr.rule=Host(`${SEERR_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.seerr.entrypoints=websecure-public"
      - "traefik.http.routers.seerr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.seerr.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.seerr.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.seerr.loadbalancer.server.port=${SEERR_PORT}"
    environment:
      - LOG_LEVEL=debug
      - JELLYFIN_TYPE=jellyfin
      - TZ=${TIMEZONE}
    # ports:
    #   - ${SEERR_PORT}:${SEERR_PORT}
    volumes:
      - ./seerr:/app/config