x-service: &service
  restart: unless-stopped
  networks:
    - media_network

x-user: &user
  <<: *service
  environment:
    - PUID=${USER_ID}
    - PGID=${GROUP_ID}
    - TZ=${TIMEZONE}

services:
  emby:
    <<: *user
    image: lscr.io/linuxserver/emby:latest
    container_name: ${EMBY_NAME}
    volumes:
      - ./emby:/config
      - shows:/data/tvshows
      - movies:/data/movies
    # ports:
    #   - ${EMBY_PORT}:${EMBY_PORT}

  jellyfin:
    <<: *user
    image: jellyfin/jellyfin:latest
    container_name: ${JELLYFIN_NAME}
    volumes:
      - ./jellyfin:/config
      - shows:/data/tvshows
      - movies:/data/movies

  jellyseerr:
    <<: *service
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: ${JELLYSEERR_NAME}
    environment:
      - LOG_LEVEL=debug
      - JELLYFIN_TYPE=jellyfin
      - TZ=${TIMEZONE}
    # ports:
    #   - ${JELLYSEERR_PORT}:${JELLYSEERR_PORT}
    volumes:
      - ./jellyseerr:/app/config