x-service: &service
  restart: unless-stopped
  networks:
    - media_network

x-user: &user
  <<: *service
  environment:
    - PUID=${USER_ID}
    - PGID=${GROUP_ID}
    - TZ=${TIMEZONE}

services:
  emby:
    <<: *user
    image: lscr.io/linuxserver/emby:latest
    container_name: ${EMBY_NAME}
    volumes:
      - ./emby:/config
      - shows:/data/tvshows
      - movies:/data/movies
    # ports:
    #   - ${EMBY_PORT}:${EMBY_PORT}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "https://${EMBY_NAME}.${DOMAIN}/emby/system/ping" ]
      interval: 30s
      retries: 10

  jellyfin:
    <<: *user
    image: jellyfin/jellyfin:latest
    container_name: ${JELLYFIN_NAME}
    group_add:
      - "992"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./jellyfin:/config
      - shows:/data/tvshows
      - movies:/data/movies
    healthcheck:
      test: [ "CMD", "curl", "--fail", "https://${JELLYFIN_NAME}.${DOMAIN}/health" ]
      interval: 30s
      retries: 10

  seerr:
    <<: *service
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: ${SEERR_NAME}
    environment:
      - LOG_LEVEL=debug
      - JELLYFIN_TYPE=jellyfin
      - TZ=${TIMEZONE}
    # ports:
    #   - ${SEERR_PORT}:${SEERR_PORT}
    volumes:
      - ./seerr:/app/config