global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: 'traefik'
    static_configs:
      - targets: ["traefik:8082"]
 