x-service: &service
  restart: unless-stopped
  networks:
    - media_network

x-user: &user
  <<: *service
  environment:
    - PUID=${USER_ID}
    - PGID=${GROUP_ID}
    - TZ=${TIMEZONE}

services:
  homarr:
    <<: *user
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: ${HOMARR_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.domain.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.domain.entrypoints=websecure"
      - "traefik.http.routers.domain.service=homarr"
      - "traefik.http.routers.domain.tls.certresolver=letsencrypt"
      - "traefik.http.routers.homarr.rule=Host(`${HOMARR_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.routers.homarr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.homarr.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.homarr.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.homarr.loadbalancer.server.port=${HOMARR_PORT}"
    volumes:
      - ./homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    # ports:
    #   - ${HOMARR_PORT}:${HOMARR_PORT}
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:${HOMARR_PORT}/" ]
      interval: 30s
      retries: 10

  filebrowser:
    <<: *user
    container_name: ${FILEBROWSER_NAME}
    image: hurlenko/filebrowser:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`${FILEBROWSER_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.filebrowser.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=${FILEBROWSER_PORT}"
    # ports:
    #   - ${FILEBROWSER_PORT}:${FILEBROWSER_INT_PORT}
    volumes:
      - /:/data/root
      - ./filebrowser:/config
      - downloads:/data/downloads
      - movies:/data/movies
      - shows:/data/shows
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:${FILEBROWSER_PORT}/health" ]
      interval: 30s
      retries: 10

  n8n:
    <<: *service
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: ${N8N_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.routers.n8n.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.n8n.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.n8n.loadbalancer.server.port=${N8N_PORT}"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${N8N_NAME}.${DOMAIN}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_NAME}.${DOMAIN}/
    volumes:
      - ./n8n:/home/node/.n8n
      - ./n8n_files:/files
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:${N8N_PORT}/healthz" ]
      interval: 30s
      retries: 10
