entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  lets-encrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: motrocgabi@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web  # This enables the HTTP challenge
      dnschallenge:
        provider: cloudflare
        delayBeforeCheck: 10
