entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  lets-encrypt:
    acme:
      email: motrocgabi@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web  # This enables the HTTP challenge
