networks:
  media_network:
    driver: bridge

volumes:
  movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4,rw,soft
      device: ":/mnt/main/media/movies"

  shows:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4,rw,soft
      device: ":/mnt/main/media/shows"

  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},nfsvers=4,rw,soft
      device: ":/mnt/main/media/downloads"
