http:
  routers:
    emby:
      rule: 'Host(`{{env "EMBY_NAME"}}.{{env "DOMAIN"}}`)'
      entryPoints:
        - "websecure"
      service: emby
      tls:
        certResolver: letsencrypt
        domains:
          - main: '{{env "DOMAIN"}}'
          - sans: '*.{{env "DOMAIN"}}'

    jellyfin:
      rule: 'Host(`{{env "JELLYFIN_NAME"}}.{{env "DOMAIN"}}`)'
      entryPoints:
        - "websecure-public"
      service: jellyfin
      tls:
        certResolver: letsencrypt
        domains:
          - main: '{{env "DOMAIN"}}'
          - sans: '*.{{env "DOMAIN"}}'

    seerr:
      rule: 'Host(`{{env "SEERR_NAME"}}.{{env "DOMAIN"}}`)'
      entryPoints:
        - "websecure-public"
      service: seerr
      tls:
        certResolver: letsencrypt
        domains:
          - main: '{{env "DOMAIN"}}'
          - sans: '*.{{env "DOMAIN"}}'


  services:
    emby:
      loadBalancer:
        servers:
          - url: http://{{env "EMBY_NAME"}}:{{env "EMBY_PORT"}}/

    jellyfin:
      loadBalancer:
        servers:
          - url: http://{{env "JELLYFIN_NAME"}}:{{env "JELLYFIN_PORT"}}/

    seerr:
      loadBalancer:
        servers:
          - url: http://{{env "SEERR_NAME"}}:{{env "SEERR_PORT"}}/
