http:
  routers:
    adguard:
      rule: 'Host(`adguard.{{env "DOMAIN"}}`)'
      entryPoints:
        - "websecure"
      service: adguard
      tls:
        certResolver: letsencrypt
        domains:
          - main: '{{env "DOMAIN"}}'
          - sans: '*.{{env "DOMAIN"}}'

    traefik:
      rule: 'Host(`traefik.{{env "DOMAIN"}}`)'
      entryPoints:
        - "websecure"
      service: api@internal
      tls:
        certResolver: letsencrypt
        domains:
          - main: '{{env "DOMAIN"}}'
          - sans: '*.{{env "DOMAIN"}}'

  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://{{env "ADGUARD_NAME"}}:80"
