http:
  serversTransports:
    lan-insecure:
      insecureSkipVerify: true

  routers:
    fry:
      rule: 'Host(`fry.couch-tomatoes.me`)'
      entryPoints:
        - "websecure"
      service: fry
      tls:
        certResolver: letsencrypt
        domains:
          - main: couch-tomatoes.me
          - sans: '*.couch-tomatoes.me'

    zoidberg:
      rule: 'Host(`zoidberg.couch-tomatoes.me`)'
      entryPoints:
        - "websecure"
      service: zoidberg
      tls:
        certResolver: letsencrypt
        domains:
          - main: couch-tomatoes.me
          - sans: '*.couch-tomatoes.me'

  services:
    fry:
      loadBalancer:
        servers:
          - url: http://192.168.0.30:7777

    zoidberg:
      loadBalancer:
        serversTransport: lan-insecure
        servers:
          - url: https://192.168.0.20
