x-service: &service
  restart: unless-stopped
  networks:
    - media_network

x-user: &user
  <<: *service
  environment:
    - PUID=${USER_ID}
    - PGID=${GROUP_ID}
    - TZ=${TIMEZONE}

include:
  - path:
    - monitoring/docker-compose.yaml
    - media/docker-compose.yaml
    - automation/docker-compose.yaml
    - management/docker-compose.yaml
    - networking/docker-compose.yaml

networks:
  media_network:
    driver: bridge